# Generated by Django 6.0.3 on 2026-03-10 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trade", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="avatar",
            field=models.ImageField(
                blank=True,
                default="avatars/default.png",
                upload_to="avatars/",
                verbose_name="用户头像",
            ),
        ),
    ]
