# Generated by Django 6.0.3 on 2026-03-10 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trade", "0002_customuser_avatar"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="order_images/",
                verbose_name="订单图片",
            ),
        ),
    ]
