# Generated by Django 6.0.3 on 2026-03-11 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trade", "0004_notification"),
    ]

    operations = [
        migrations.AddField(
            model_name="transport",
            name="description",
            field=models.TextField(blank=True, null=True, verbose_name="物流描述"),
        ),
        migrations.AddField(
            model_name="transport",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="transport/", verbose_name="物流图片"
            ),
        ),
    ]
