# Generated by Django 6.0.3 on 2026-03-11 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trade", "0005_transport_description_transport_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="news",
            name="image_url",
        ),
        migrations.AddField(
            model_name="news",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="news_images/", verbose_name="封面图"
            ),
        ),
    ]
