# Generated by Django 6.0.3 on 2026-03-11 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("trade", "0006_remove_news_image_url_news_image"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="company",
            options={"verbose_name": "公司", "verbose_name_plural": "公司信息"},
        ),
    ]
