# Generated by Django 6.0.3 on 2026-03-11 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trade", "0007_alter_company_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="company",
            options={"verbose_name": "公司", "verbose_name_plural": "公司"},
        ),
        migrations.AddField(
            model_name="company",
            name="contact_person",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="联系人"
            ),
        ),
    ]
