# Generated by Django 6.0.3 on 2026-03-11 21:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trade", "0008_alter_company_options_company_contact_person"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="company_images/",
                verbose_name="公司图片",
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="intro",
            field=models.TextField(
                blank=True, max_length=500, null=True, verbose_name="公司简介"
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="companies",
                to=settings.AUTH_USER_MODEL,
                verbose_name="关联用户",
            ),
        ),
    ]
