"""
Django settings for TradeNewPlatForm project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os
from django.utils.translation import gettext_lazy as _

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-cl6-(0l!zfkan+=vxf*jui$(#mrpc85z4(%ar%w1e_t!++p))="

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
ALLOWED_HOSTS = []

# Specify custom user model
AUTH_USER_MODEL = 'trade.CustomUser'

# Application definition
INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.contenttypes",
    "django.contrib.auth",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "trade",
    'administrator',  # Administrator backend (completely independent App)
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    'django.middleware.locale.LocaleMiddleware',  # Language middleware (must be placed after CommonMiddleware)
]

ROOT_URLCONF = "TradeNewPlatForm.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / 'templates'],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "TradeNewPlatForm.wsgi.application"

# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'trade_platform',  # Database name (need to create manually)
        'USER': 'root',  # Database username
        'PASSWORD': 'AEAEAEEOO',  # Database password
        'HOST': 'localhost',
        'PORT': '3306',
        'OPTIONS': {
            'charset': 'utf8mb4'
        }
    }
}

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators
AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/
LANGUAGE_CODE = "en-us"
TIME_ZONE = "UTC"
USE_I18N = True
USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/
STATIC_URL = "static/"
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]  # Point to the root static directory

# Login page URL (consistent with the login route in your urls.py)
LOGIN_URL = '/login/'
# Default redirect page after login
LOGIN_REDIRECT_URL = '/'

# Add at the end of settings.py
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Add at the end of settings.py
# 1. Set session expiration time to 7 days (unit: seconds), adjustable as needed
SESSION_COOKIE_AGE = 60 * 60 * 24 * 7
# 2. Session does not expire immediately after closing the browser (key: avoid logout on browser close)
SESSION_EXPIRE_AT_BROWSER_CLOSE = False
# 3. Automatically refresh session expiration time on each request (extend login status)
SESSION_SAVE_EVERY_REQUEST = True

# Enable internationalization
USE_I18N = True  # Enable internationalization
USE_L10N = True  # Enable localization (date/number formats, etc.)
USE_TZ = True

# Supported languages (English as default, Chinese as optional)
LANGUAGES = [
    ('en', _('English')),   # English
    ('zh-hans', _('Simplified Chinese')),  # Simplified Chinese
]

# Language file storage path (create a new locale folder)
LOCALE_PATHS = [
    os.path.join(BASE_DIR, 'locale'),  # Locale folder in the project root directory
]

# Default language (English)
LANGUAGE_CODE = 'en'
