"""
Django settings for TradeNewPlatForm project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os
from django.utils.translation import gettext_lazy as _


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-cl6-(0l!zfkan+=vxf*jui$(#mrpc85z4(%ar%w1e_t!++p))="

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

# 指定自定义用户模型
AUTH_USER_MODEL = 'trade.CustomUser'

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "trade",
    'administrator',  # 管理员端（全新独立 App）
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    'django.middleware.locale.LocaleMiddleware',  # 语言中间件（需放在 CommonMiddleware 之后
]

ROOT_URLCONF = "TradeNewPlatForm.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / 'templates']
        ,
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "TradeNewPlatForm.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'trade_platform',  # 数据库名（需手动创建）
        'USER': 'root',  # 数据库用户名
        'PASSWORD': 'AEAEAEEOO',  # 数据库密码
        'HOST': 'localhost',
        'PORT': '3306',
        'OPTIONS': {
            'charset': 'utf8mb4'
        }
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "static/"
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]  # 指向根目录 static

# 登录页URL（和你的urls.py中登录路由一致）
LOGIN_URL = '/login/'
# 登录后默认跳转页
LOGIN_REDIRECT_URL = '/'

# settings.py 末尾添加
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# settings.py 末尾添加
# 1. 设置 Session 有效期为 7 天（单位：秒），可根据需求调整
SESSION_COOKIE_AGE = 60 * 60 * 24 * 7
# 2. 关闭浏览器后 Session 不立即失效（关键：避免关浏览器就登出）
SESSION_EXPIRE_AT_BROWSER_CLOSE = False
# 3. 每次请求自动刷新 Session 有效期（延长登录状态）
SESSION_SAVE_EVERY_REQUEST = True


# 开启国际化
USE_I18N = True  # 启用国际化
USE_L10N = True  # 启用本地化（日期/数字格式等）
USE_TZ = True

# 支持的语言（英文为默认，中文为可选）
LANGUAGES = [
    ('en', _('English')),   # 英文
    ('zh-hans', _('Simplified Chinese')),  # 简体中文
]

# 语言文件存放路径（新建 locale 文件夹）
LOCALE_PATHS = [
    os.path.join(BASE_DIR, 'locale'),  # 项目根目录下的 locale 文件夹
]

# 默认语言（英文）
LANGUAGE_CODE = 'en'
